### ISSUE TITLE
Missed password step [Import wallet flow]

### ISSUE THREAD

**Issue by ant-mad** [SnaxFoundation/snax-browser-extension#16]
When extension was closed before password set in import wallet flow, popup reopens with /wallet route instead of /password.

**Comment by SnaxOne** [comment]
We need 2 things here:
1. Clear passowrd first before clearing key in 'Restore wallet' flow.
2. Swapped password and mnemonic steps in 'Import wallet' flow.

In both cases we will not lose the state if popup was closed.
