### ISSUE TITLE
Fix data check in Import Wallet flow

### ISSUE THREAD

**Issue by pinknumbat** [SnaxFoundation/snax-browser-extension#22]
1. Register new wallet
2. Copy public key
3. Lock wallet
4. Pick 'Import wallet'
5. Enter a random password
6. Enter public key, copied in step 2, and distribute it into 12 words

Result: You're logged in a wallet with the same public key as you copied in step 2.

**Comment by ant-mad** [comment]
Not the same 
But extension needs to check mnemonic words to be more user-friendly

**Comment by theBigChups** [comment]
Won't do it. Useless and can be insecure in the case of remote dictionary.
