### ISSUE TITLE
Remove dialog opening on click

### ISSUE THREAD

**Issue by pinknumbat** [SnaxFoundation/snax-browser-extension#30]
- [x] Windows shouldn’t be opened in a separate after some UI click, including Transaction Confirmation Screen
- [x] Show notification label if there’re any incoming notifications (transactions requests), badge colour - red  - 
https://developer.chrome.com/extensions/browserAction#method-setBadgeText

**Comment by bee-warrior** [comment]
https://github.com/SnaxFoundation/snax-browser-extension/pull/33
