### ISSUE TITLE
Badge is grey even on domestic domain

### ISSUE THREAD

**Issue by pinknumbat** [SnaxFoundation/snax-browser-extension#40]
<img width="665" alt="2019-02-20 3 02 30" src="https://user-images.githubusercontent.com/45242307/53056463-579e5100-34bc-11e9-9755-21c6a850afba.png">

https://github.com/SnaxFoundation/snax-browser-extension/pull/52

**Comment by bee-warrior** [comment]
@pinknumbat Cannot reproduce this issue. Is it still actual problem?

**Comment by pinknumbat** [comment]
@bee-warrior still actual

<img width="811" alt="2019-02-25 15 45 17" src="https://user-images.githubusercontent.com/45242307/53338307-68175700-3914-11e9-8dce-4f443867d327.png">
