### ISSUE TITLE
Invalid transaction

### ISSUE THREAD

**Issue by pinknumbat** [SnaxFoundation/snax-browser-extension#41]
I've ran into an invalid transaction somehow and can't cancel it - do we have a timeout?

We should prevent submitting invalid data to the extension. If that's happened, show transaction screen with the corresponding error.

<img width="849" alt="2019-02-20 3 03 18" src="https://user-images.githubusercontent.com/45242307/53056484-68e75d80-34bc-11e9-9490-c4018f91a87b.png">

<img width="991" alt="2019-02-20 3 07 09" src="https://user-images.githubusercontent.com/45242307/53056533-a4822780-34bc-11e9-91b3-f8f123d8e79a.png">

**Comment by bee-warrior** [comment]
fixed
https://github.com/SnaxFoundation/snax-browser-extension/pull/49
