### ISSUE TITLE
Show status screen after completing transaction

### ISSUE THREAD

**Issue by pinknumbat** [SnaxFoundation/snax-browser-extension#51]
- [x] Show success screen on success
- [ ] Show error screen on error
- [x] Hide screen on timeout or 'back to wallet' button

**Comment by theBigChups** [comment]
@pinknumbat And also we have to make loader between 'Confirm' button has been clicked and transaction was sent. Because this time interval can be very floating.

**Comment by pinknumbat** [comment]
@bee-warrior 
see SuccessRoute, ErrorRoute
to show processing status put 'loading' prop on 'Confirm' button
