### ISSUE TITLE
Hide extension after transaction success or error

### ISSUE THREAD

**Issue by pinknumbat** [SnaxFoundation/snax-browser-extension#86]
Now after a transaction, we show status screen: error or success. It leads a user to the wallet screen after timeout or button click.

- [ ] Change text on Button to 'Ok'
- [ ] Instead of leading user to the wallet screen we should hide extension window by the button click or timeout.

**Comment by bee-warrior** [comment]
https://github.com/SnaxFoundation/snax-browser-extension/pull/89
